#===================#
#== Env Variables ==#
#===================#
DOCKER_COMPOSE_FILE ?= ../docker-compose.yml


#========================#
#== DATABASE MIGRATION ==#
#========================#

migrate-up: ## Run migrations UP
	docker-compose -f ${DOCKER_COMPOSE_FILE} --profile tools run --rm migrate up

migrate-down: ## Rollback migrations against non test DB
	docker-compose -f ${DOCKER_COMPOSE_FILE} --profile tools run --rm migrate down 1

migrate-create: ## Create a DB migration files e.g `make migrate-create name=migration-name`
	docker-compose -f ${DOCKER_COMPOSE_FILE} --profile tools run --rm migrate create -ext sql -dir /migrations $(name)

migrate-force: ## Force migration version e.g `make migrate-force version=migration-version`
	docker-compose -f ${DOCKER_COMPOSE_FILE} --profile tools run --rm migrate force $(version)

shell-db: ## Enter to database console
	docker-compose -f ${DOCKER_COMPOSE_FILE} exec db psql -U postgres -d postgres
